version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=https://cachengoclub.com:8080
      - LETSENCRYPT_HOST=https://cachengoclub.com:8080